blank_issues_enabled: true
contact_links:
  - name: "Discord Server"
    url: https://vanillaos.org/community
    about: "Consider joining the Discord Server to discuss your issue, question or suggestion with the community before opening an issue."
